cu_cp:
  max_nof_dus:                          # Optional UINT. Maximum number of DU connections that the CU-CP may accept.
  max_nof_cu_ups:                       # Optional UINT. Maximum number of CU-UP connections that the CU-CP may accept.
  max_nof_ues:                          # Optional UINT. Maximum number of UEs that the CU-CP may accept.
  max_nof_drbs_per_ue:                  # Optional UINT. Maximum number of DRBs per UE. Supported: [1 - 29].
  inactivity_timer: 120                 # Optional INT (120). Sets the UE/PDU Session/DRB inactivity timer in seconds. Supported: [1 - 7200].
  request_pdu_session_timeout: 3        # Optional INT (3). Timeout for the setup of a PDU session after an InitialUeMessage was sent to the core, in seconds. The timeout must be larger than T310. If the value is reached, the UE will be released

  rrc:
    force_reestablishment_fallback: false    # Optional BOOLEAN (false). Force RRC re-establishment fallback to RRC setup. Supported: [false, true].
    rrc_procedure_timeout_ms: 720            # Optional UINT (720). Sets the timeout in ms used for RRC message exchange with UE. It needs to suit the expected communication delay and account for potential retransmissions UE processing delays, SR delays, etc. Supported: [0 - inf].
  
  security:
    integrity: not_needed                    # Optional TEXT (not_needed). Sets the default integrity protection indication for DRBs.
    confidentiality: required                # Optional TEXT (required). Sets the default integrity confidentiality indication for DRBs.
    nea_pref_list: nea0,nea2,nea1            # Optional TEXT (nea0,nea2,nea1). Ordered preference list for the selection of encryption algorithm (NEA). Supported: [nea0,nea2,nea1,nea3].
    nia_pref_list: nia2,nia1                 # Optional TEXT (nia2,nia1). Ordered preference list for the selection of encryption algorithm (NIA). Supported: [nia2,nia1,nia3].

  f1ap:
    procedure_timeout: 1000                  # Optional INT (1000). Sets the time the F1AP waits for a DU response in milliseconds.

  e1ap: 
    procedure_timeout: 1000                  # Optional INT (1000). Sets the time the E1AP waits for a CU-UP response in milliseconds.

  mobility:
    trigger_handover_from_measurements: false   # Optional BOOLEAN (false). Sets whether or not to start HO if neighbor cells become stronger. Supported: [false, true].
    cells:                                      # Optional TEXT. Sets the list of cells known to the CU-CP, their configs (if not provided over F1) and their respective neighbor cells.
      -                                         # Define Cell 1
        nr_cell_id:                               # Required UINT. The ID of this serving cell.
        periodic_report_cfg_id:                   # Optional UINT. The periodical report configuration to use for this serving cell.
        ncells:                                   # Required TEXT. List of neighbor cells.
          nr_cell_id:                                 # Required UINT. The ID of this neighbor cell.
          report_configs:                             # Required TEXT. List of report configurations to use for measurements of this neighbor cell.
        gnb_id_bit_length:                        # Optional UINT. The ID of this gNB. Supported: [22 - 32]
        pci:                                      # Optional UINT. The PCI of this serving cell. Supported: [0-1007]
        band:                                     # Optional UINT. The NR band of this serving cell cell. Must be present if not provided over F1.
        ssb_scs:                                  # Optional UINT. The SSB subcarrier spacing of this serving cell in KHz. Must be present if not provided over F1.
        ssb_period:                               # Optional UINT. The SSB period of this serving cell in ms.  Must be present if not provided over F1.
        ssb_offset:                               # Optional UINT. The SSB offset of this serving cell. Must be present if not provided over F1.
        ssb_duration:                             # Optional UINT. The SSB duration of this serving cell in subframes. Must be present if not provided over F1.
    report_configs:                             # Optional TEXT. Sets the list of report configurations to dynamically build a measurement configuration sent to the UEs using the below values.
      -                                         # Define report configs for cell 1
        report_cfg_id:                            # Required UINT. The ID of this report configuration.
        report_type:                              # Required TEXT. The type of the report. Supported: [event_triggered, periodical]. Note that periodical reports are only supported for serving cells.
        event_triggered_report_type:              # Optional TEXT. Sets the type of event triggered report. Supported: [a1, a2, a3, a4, a5, a6].
        report_interval_ms: 1024                  # Optional UINT (1024). The report interval in ms. Supported: [120, 240, 480, 640, 1024, 2048, 5120, 10240, 20480, 40960, 60000, 360000, 720000, 1800000]. 
        meas_trigger_quantity:                    # Optional TEXT. Sets the quantity to be measured. Supported: [rsrp, rsrq, sinr]. 
        meas_trigger_quantity_threshold_db:       # Optional UINT. Sets the measurement trigger quantity threshold in dB used for measurement report trigger of event A1/A2/A4/A5. Supported: [0 - 127].
        meas_trigger_quantity_threshold_2_db:     # Optional UINT. Sets the measurement trigger quantity threshold 2 in dB used for measurement report trigger of event A5. Supported: [0 - 127].
        meas_trigger_quantity_offset_db:          # Optional UINT. Sets the measurement trigger quantity offset in dB used for measurement report trigger of event A3/A6. Note the actual value is field value * 0.5 dB. Supported: [-30 - 30].
        hysteresis_db:                            # Optional UINT. Sets the hysteresis in dB used for measurement report trigger. Note the actual value is field value * 0.5 dB. Supported: [0 - 30].
        time_to_trigger_ms:                       # Optional UINT. Sets the time in ms during which a condition must be met before measurement report trigger. Supported: [0, 40, 64, 80, 100, 128, 160, 256, 320, 480, 512, 640, 1024, 1280, 2560, 5120]. 

cu_up:
  warn_on_drop: false                   # Optional BOOLEAN (false). Enables the option to log a warning for dropped packets in GTP-U and PDCP due to full queues. Supported: [false, true].

  ngu: 
    no_core: false                        # Optional BOOLEAN (false). Setting to true allows the gNB to run without a core. Supported: [0, 1].
    socket:                               # Define socket(s) for NG-U interface.
      -                                     # Socket 1 
        bind_addr: 127.0.3.1                  # Optional TEXT (auto). Sets local IP address to bind for N3 interface. Format: IPV4 or IPV6 IP address.
        udp:
          max_rx_msgs: 256                      # Optional INT (256). Sets the maximum number of messages RX from a socket in a single syscall.
          pool_threshold: 0.9                   # Optional FLOAT (0.9). Sets the pool occupancy threshold, after which packets are dropped. Supported: [0.0 - 1.0].
          dscp:                                 # Optional UINT. Sets the Differentiated Services Code Point. Supported: [0 - 63].
    gtpu: 
      queue_size: 2046                       # Optional UINT (2046). GTP-U queue size, in PDUs
      batch_size: 256                        # Optional UINT (256). Maximum number of GTP-U PDUs processed in a batch
      reordering_timer: 0                    # Optional UINT (0). GTP-U RX reordering timer (in milliseconds)
      rate_limiter_period:                   # Optional INT. GTP-U RX rate limiter period (in milliseconds)
      ignore_ue_ambr: true                   # Optional BOOLEAN (true). Ignore GTP-U DL UE-AMBR rate limiter

  test_mode:
    enable: false                         # Optional BOOLEAN (false). Enable or disable CU-UP test mode
    integrity_enable: false               # Optional BOOLEAN (false). Enable or disable PDCP integrity testing
    ciphering_enable: false               # Optional BOOLEAN (false). Enable or disable PDCP ciphering testing
    nea_algo: 2                           # Optional UINT:INT (2). NEA algo to use for testing. Format: [0 - 3]
    nia_algo: 2                           # Optional UINT:INT (2). NIA algo to use for testing. Format: [1 - 3]
    ue_ambr:                              # Optional UINT. DL UE-AMBR used for testing in bps
    attach_detach_period:                 # Optional INT. Attach/detach period for test mode. 0 means always attached.

du:
  warn_on_drop: false                   # Optional BOOLEAN (false). Enables the option to log a warning for dropped packets in RLC and MAC due to full queues. Supported: [false, true].

cell_cfg:
  sib:
    si_window_length: 160                   # Optional UINT (160). Sets the length of the SI scheduling window, in slots. It must be always shorter or equal to the period of the SI message. Supported: [5,10,20,40,80,160,320,640,1280].
    si_sched_info:                          # Optional TEXT. Configures the scheduling for each of the SI-messages broadcast by the gNB.
    t300: 1000                              # Optional UINT (1000). Sets the RRC Connection Establishment timer in ms. The timer starts upon transmission of RRCSetupRequest. Supported: [100,200,300,400,600,1000,1500,2000].
    t301: 1000                              # Optional UINT (1000). Sets the RRC Connection Re-establishment timer in ms. The timer starts upon transmission of RRCReestablishmentRequest. Supported: [100,200,300,400,600,1000,1500,2000].
    t310: 1000                              # Optional UINT (1000). Sets the Out-of-sync timer in ms. The timer starts upon detecting physical layer problems for the SpCell i.e. upon receiving N310 consecutive out-of-sync indications from lower layers. Supported: [0,50,100,200,500,1000,2000].
    n310: 1                                 # Optional UINT (1). Sets the Out-of-sync counter. The counter is increased upon reception of "out-of-sync" from lower layer while the timer T310 is stopped. Starts the timer T310, when configured value is reached. Supported: [1,2,3,4,6,8,10,20].
    t311: 3000                              # Optional UINT (3000). Sets the RRC Connection Re-establishment procedure timer in ms. The timer starts upon initiating the RRC connection re-establishment procedure. Supported: [1000,3000,5000,10000,15000,20000,30000].
    n311: 1                                 # Optional UINT (1). Sets the In-sync counter. The counter is increased upon reception of the "in-sync" from lower layer while the timer T310 is running. Stops the timer T310, when configured value is reached.Supported: [1,2,3,4,5,6,8,10].
    t319: 1000                              # Optional UINT (1000). Sets the RRC Connection Resume timer in ms. The timer starts upon transmission of RRCResumeRequest or RRCResumeRequest1. Supported: [100,200,300,400,600,1000,1500,2000].
    etws: 
      message_id: 4356                        # Optional UINT (4356). Sets the ETWS message ID. Supported: [0 - 65535].
      serial_num: 1288                        # Optional UINT (1228). Sets the ETWS serial number. Supported: [0 - 65535].
      warning_type: 2432                      # Optional UINT (2432). Sets the ETWS warning type. Supported: [0 - 65535].
      data_coding_scheme: 0                   # Optional UINT (0). Sets the ETWS data coding scheme. Supported: [0 - 255].
      warning_message:                        # Optional TEXT. Sets the ETWS warning message. Max length and character support depends on the chosen coding scheme. 
    cmas:
      message_id: 4370                        # Optional UINT (4370). Sets the CMAS message ID. Supported: [0 - 65535].
      serial_num: 12291                       # Optional UINT (12291). Sets the CMAS serial number. Supported: [0 - 65535].
      data_coding_scheme: 0                   # Optional UINT (0). Sets the CMAS data coding scheme. Supported: [0 - 255].
      warning_message:                        # Optional TEXT. Sets the CMAS warning message. Max length and character support depends on the chosen coding scheme.
